import HotDealsCards from "@/components/HotDealsCards";
import Head from "next/head";
import Link from 'next/link';
import Packages from "../../db.json";
import React, { useState, useEffect } from "react";
import DatePicker from "react-datepicker";

import "react-datepicker/dist/react-datepicker.css";

export default function Home() {
    const [startDate, setStartDate] = useState(new Date());
    const [endDate, setEndDate] = useState(new Date());
    useEffect(() => {
        localStorage.setItem("startDate", startDate);
        localStorage.setItem("endDate", endDate);
    }, [startDate, endDate]);

    const [zone, setZone] = useState("")

    const onZoneChange = (e) => {
        setZone(e.target.value)
    }

    return (
        <>
            <Head>
                <title>Galaxia Getaways</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <section style={{ color: "white", padding: "1rem" }}>
                <div className="container">
                    <div className="search_panel">
                        <h2>Browse Interplanetary Destinations</h2>
                        <div className="outer-panel"> 
                        <div className="panel">
                            <div className="check_in">
                                Check in date:
                                <DatePicker
                                    selected={startDate}
                                    onChange={(date) => {
                                        if (date > endDate) {
                                            console.log(
                                                "please select earlier date than checkout date"
                                            );
                                        }
                                        setStartDate(date);
                                    }}
                                />
                                <p
                                    className="error_message"
                                    style={
                                        startDate > endDate
                                            ? { display: "block" }
                                            : { display: "none" }
                                    }>
                                    Check-in date cannot be later than check-out
                                    date.
                                </p>
                            </div>
                            <div className="check_out">
                                Check out date:
                                <DatePicker
                                    selected={endDate}
                                    onChange={(date) => setEndDate(date)}
                                />
                            </div>
                        </div>
                        <div className="search">
                            <select name="package_select" id="package_select" onChange={onZoneChange}>
                                <option value="">
                                    Select Solar System Zone
                                </option>
                                <option value="inner">
                                    Inner Solar System
                                </option>
                                <option value="outer">
                                    Outer Solar System
                                </option>
                                <option value="moon">The Moon (Earth-Zone)</option>
                            </select>
                            <Link href={{
                                        pathname: "/results",
                                        query: { zone: zone },
                                      }}>
                            <button>Discover</button>
                            </Link>
                            </div>

                        </div>
                    </div>

                    <div className="hotdeals_container">
                        <div className="deals">
                            {Packages.filter(
                                (planetPackages) => planetPackages.hotDeals
                            ).map((planetPackages, i) => {
                                if (i > 8) {
                                    return;
                                }
                                return (
                                    <Link href={{
                                        pathname: "/checkout",
                                        query: { id: `${planetPackages.id}` },
                                      }}
                                      style={{textDecoration: "none"}}>
                                    <HotDealsCards
                                        packageName={planetPackages.packageName}
                                        image={planetPackages.image}
                                        location={planetPackages.location}
                                        price={planetPackages.price}
                                    />
                                    </Link>
                                );
                            })}
                        </div>
                    </div>
                </div>
            </section>
            <style jsx>
                {`
                    .hotdeals_container {
                        // background: #fcf7ff;
                        background-color: #403e47;
                        width: 100%;
                        max-width: 1200px;
                        height: 70vh;
                        padding: 1.5rem 1rem;
                        border-radius: 8px;
                        margin-left: auto;
                        overflow: scroll;
                    }
                    .deals {
                        display: grid;
                        grid-template-columns: repeat(
                            auto-fill,
                            minmax(285px, 1fr)
                        );
                        grid-gap: 1em;
                    }
                    .container {
                        display: flex;
                        margin-top: 2rem;
                    }
                    .search_panel {
                        // background: #fcf7ff;
                        background-color: #403e47;
                        width: 100%;
                        max-width: 600px;
                        color: gainsboro;
                        margin-right: 1rem;
                        max-height: 300px;
                        border-radius: 8px;
                        display: flex;
                        flex-direction: column;
                        align-items: center;
                    }
                    .search_panel .panel {
                        display: flex;
                        gap: 1rem;
                    }
                    .outer-panel {
                        height: 70%;

                    }
                    .search_panel .search {
                        margin-top: 1rem;
                    }
                    .search_panel .search select {
                        -webkit-appearance: none;
                        -moz-appearance: none;
                        background-image: url("data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/><path d='M0 0h24v24H0z' fill='none'/></svg>");
                        background-repeat: no-repeat;
                        background-position-x: 98%;
                        background-position-y: 50%;
                        margin-top: 1rem;
                        margin-bottom: 1rem;
                        border: 1px solid grey;
                        border-radius: 3px;
                        padding: 0.45rem 0.5rem;
                        width: 100%;
                        min-width: 225px;
                        font-size: 1rem;
                    }
                    .search_panel .search button {
                        cursor: pointer;
                        width: 100%;
                        border-radius: 5px;
                        padding: 0.45rem 1rem;
                        display: block;
                        margin: auto;
                        font-size: 1rem;
                        color: white;
                        background: #9182ec;
                        border: none;
                    }
                    .search_panel .search button:hover {
                        background: #8878eb;
                    }
                    .button > * {
                        text-decoration: none;
                    }
                    .error_message {
                        color: red;
                        font-size: 12px;
                        // font-weight: 600;
                        position: absolute;
                        margin: 0;
                    }
                `}
            </style>
        </>
    );
}
